### ISSUE TITLE
Cannot run preprocess.py

### ISSUE THREAD

**Issue by Nauw1010** [JaeLee18/ACM-TOG-Latent-L-systems-Transformer-based-Tree-Generator#2]
Hi!
I am trying to run the preprocess.py script but I found that maybe the utils are missing from the repository. Line 21 in preprocess.py imports utils but there are no utils in the code. I will be appreciated if you could update us the code! Thank you!

**Comment by NikolaiCSp** [comment]
> Hi! I am trying to run the preprocess.py script but I found that maybe the utils are missing from the repository. Line 21 in preprocess.py imports utils but there are no utils in the code. I will be appreciated if you could update us the code! Thank you!

Hello, I am struggling with the same issue. I was wondering if you found a solution to it. Thank you in advance.

**Comment by JaeLee18** [comment]
Please check `utils.py`
