### ISSUE TITLE
After training, how to use the config. json, best. psh, and best. psh

### ISSUE THREAD

**Issue by jacksea001** [JaeLee18/ACM-TOG-Latent-L-systems-Transformer-based-Tree-Generator#3]
1 After training, how to use the config. json, best. psh, and best. psh files obtained from the bird-train_all file?
2 Can you directly load it into your UniEngine and convert it to 3D mesh?

**Comment by jacksea001** [comment]
1 After training, how to use the config. json, best. pth?
2 Can you directly load it into your UniEngine and convert it to 3D mesh?

**Comment by suptimq** [comment]
Hey did you successfully run the `preprocessing.py`? I figured there is one function missing.
https://github.com/JaeLee18/ACM-TOG-Latent-L-systems-Transformer-based-Tree-Generator/blob/main/utils.py#L86

Appreciate the help!

**Comment by JaeLee18** [comment]
1. Please check `generate.py` to use files from the preprocessing and training.
2. Yes, using `PlantArchitect` https://github.com/edisonlee0212/PlantArchitect, you can load *.lstring file. I will make a tutorial for this.
